import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { NavBar } from '../components/commons/NavBar'
export default function aboutPage() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About - Reneloper</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Ir a  <Link href={'/'} >index!</Link>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/about.jsx</code>
                </p>
            </main>
        </div>
    )
}

