import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { NavBar } from '../components/commons/NavBar'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Reneloper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />


      <main className={styles.main}>
        <h1 className={"text-3xl font-bold underline text-red-600"}>
          Home
        </h1>

        <h1 className={styles.title}>
          Ir a <Link href="/about">Acerca de mí!</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>


      </main>

    </div>
  )
}
